Changed validate script to validate all geo.json files

diff --git a/validate b/validate
--- a/validate
+++ b/validate
@@ -1,11 +1,27 @@
-#!/bin/sh
+#! /bin/sh
 
-result=$(curl -X POST --data @hyperboria.geo.json $data http://geojsonlint.com/validate 2>/dev/null)
+files=`find . -type f | egrep '\.geo\.json$'`
+file_count=0
+failures=()
 
-if [ "$result" = "{\"status\": \"ok\"}" ]; then
-  echo "Valid geoJSON!"
-  exit 0
+for file in $files
+do
+    echo 'Testing '$file
+    (( file_count += 1 ))
+    result=$(curl -X POST --data @$file $data http://geojsonlint.com/validate 2>/dev/null)
+    if [ "$result" = "{\"status\": \"ok\"}" ]; then
+        echo "    Valid GeoJSON"
+    else
+        echo "    Invalid GeoJSON"
+        failures+=($file)
+    fi
+done
+
+error_count="${#failures[@]}"
+echo $file_count files checked. $error_count failures.
+
+if [ "$error_count" = 0 ]; then
+    exit 0
 else
-  echo "Invalid geoJSON"
-  exit 1
+    exit 1
 fi
